### ISSUE TITLE
[Bug] image can't output in jupyter notebook

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/open-digger#1128] opened 2023-01-08 15:31 UTC
This is the first time I have used the function in opendigger to do data analysis.

I want to add open rank data analysis of  application_domain repository in China_open_source_report_2022.ipynb.

I finish it according to the existing code, but the image could not be output. 

The data has indeed been obtained.

After I executed the npm install and npm run build commands, I started jupyter notebook.

I'm not sure if there is a problem with my local environment.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/29674550/211204639-f0f60d57-378e-4c44-b58c-9289c53a3e6e.png">

**Comment by frank-zsy** [comment] 2023-01-09 06:37
@PureNatural Can you comment your code as text form so we can try it out, or you can just raise a PR with the change, that could be better.

**Comment by PureNatural** [comment] 2023-01-09 07:54
Ok, thanks for your reply. I will do it.

**Comment by PureNatural** [comment] 2023-01-10 08:24
We shuold use `npm run notebook` to start the notebook instead of using `jupyter notebook`.

Developers who use opendigger for the first time need to pay attention.

**Comment by PureNatural** [comment] 2023-01-10 10:15
This document describes the use of opendigger clearly. I didn't notice it before.
Thanks! @tyn1998

**Comment by xgdyp** [comment] 2023-01-10 10:52
I test this in vscode jupyter notebook plugin. It did not render the image. But if we use our jupyter image, it can.
I also test the ijs-plotly lib. It can render images successfully.
![image](https://user-images.githubusercontent.com/37795442/211531483-fbf6c7c3-e178-4aa1-b831-6735835e2cc6.png)
If we define a variable and plot, it can render, too.
![image](https://user-images.githubusercontent.com/37795442/211531924-4357eee0-1aa6-4447-ac87-6a783156cb09.png)
But if we plot directly after get data in one cell, it can't.
![image](https://user-images.githubusercontent.com/37795442/211532204-bdcb6fc5-bbf8-49c4-bbd1-c7b525829f7e.png)
I'm not sure if it caused by `promise` or jupyter version.

**Comment by xgdyp** [comment] 2023-01-10 10:53
Do you have any idea on this? @tyn1998 @frank-zsy

**Comment by frank-zsy** [comment] 2023-01-12 04:04
@xgdyp I did not use vscode notebook plugin at all, it may involve the behavior of the plugin. You should always use our notebook image to run OpenDigger.

**Comment by frank-zsy** [comment] 2023-02-26 01:55
Is there any update on this one? @xgdyp

**Comment by xgdyp** [comment] 2023-03-22 05:20
Hi, I test some methods before but there is no use. I think we can close it.

**Closed** 2023-03-29 01:45 UTC
Labels: kind/bug, waiting for author
